services:
  - type: web
    name: splitwise-member-backend
    env: python
    buildCommand: "pip install -r requirements.txt"
    startCommand: "uvicorn app:app --host 0.0.0.0 --port $PORT"
    envVars:
      - key: MONGO_URL
        sync: false
      - key: DATABASE_NAME
        value: splitwise_ai
      - key: CLERK_PEM_PUBLIC_KEY
        sync: false
      - key: CLERK_JWT_AUDIENCE
        sync: false
      - key: SPLITWISE_CONSUMER_KEY
        sync: false
      - key: SPLITWISE_SECRET_KEY
        sync: false
      - key: SPLITWISE_API_KEY
        sync: false
      - key: ADMIN_EMAILS
        sync: false
      - key: NODE_ENV
        value: production